Improved input syntax for `frequency_differencing` operation
OSOceanAcoustics/echopype pull request #1106
Opened 2023-07-31 18:00 UTC by praneethratna

Addresses #967. Now input for frequency_differencing can be given directly in the form of frequency differencing criteria instead of separating out freq/chan from operators.

2023-07-31 18:27 UTC, emiliom commented
These improvements are very cool! 

Since you're adding `sympy` as a dependency, how "heavy" a library is it? In other words, is it likely to create dependency resolution issues? I see the dependency tree `sympy > mpmath > gmpy2`, where [gmpy2](https://github.com/aleaxit/gmpy) apparently uses a C library ("gmpy2 is an optimized, C-coded Python extension module  ...").

Are there lighter-weight alternatives to `sympy` that would meet our needs? sympy has tons of capabilities, and here I think we'd be using only a tiny subset.

2023-07-31 18:28 UTC, emiliom commented on requirements-dev.txt
> +sympy
I don't think sympy needs to go here, too. It only needs to be in `requirements.txt`
```suggestion
```

2023-07-31 18:39 UTC, praneethratna commented
> These improvements are very cool! 
> 
> Since you're adding `sympy` as a dependency, how "heavy" a library is it? In other words, is it likely to create dependency resolution issues? I see the dependency tree `sympy > mpmath > gmpy2`, where [gmpy2](https://github.com/aleaxit/gmpy) apparently uses a C library ("gmpy2 is an optimized, C-coded Python extension module  ...").

I feel `SymPy` is lightweight compated compared to other mathematical libraries found online. Also `SymPy` has a hard dependency only on mpmath but I don't it would create dependency resolution issues.

> 
> Are there lighter-weight alternatives to `sympy` that would meet our needs? sympy has tons of capabilities, and here I think we'd be using only a tiny subset.

I'm using `SymPy` for parsing numbers from strings using it's inbuilt parser. I'm not sure of any other libraries which can be used for this.

2023-07-31 18:45 UTC, emiliom commented
> Also SymPy has a hard dependency only on mpmath but I don't it would create dependency resolution issues.

Right! Scratch my comment about dependency resolution per se. I did see that the dependency was limited to mpmath > gmpy2, and we don't currently use those libraries. My apologies.

2023-08-01 05:43 UTC, praneethratna commented
> > Also SymPy has a hard dependency only on mpmath but I don't it would create dependency resolution issues.
> 
> Right! Scratch my comment about dependency resolution per se. I did see that the dependency was limited to mpmath > gmpy2, and we don't currently use those libraries. My apologies.

No worries! I understand the clarification now. Since we don't use mpmath or gmpy2 libraries, these dependencies doesn't affect us. But we need to look at alternatives for `SymPy` if that makes the package slow.

2023-08-01 06:14 UTC, leewujung commented
Since the equations are pretty predictable, one option would be to just do `re` all the way?

2023-08-01 08:06 UTC, praneethratna commented
> Since the equations are pretty predictable, one option would be to just do `re` all the way?

You mean we use a single regex expression to check for the validity of the whole frequency differencing criteria? Wouldn't that make the code a bit messy?

2023-08-02 21:06 UTC, leewujung commented
> @leewujung Do you mean we use a single regex expression to check for the validity of the whole frequency differencing criteria? Wouldn't that make the code a bit messy?

I think it would be ok? For the freqAB case, the `Hz/kHz/MHz/GHz` cases are fixed, so the number in front of that could be extracted. For the chanAB case, it is the string between the double quotes. The binary comparison operator `>, <, >=, <=, ==` are the allowed cases. And then we need to extracted the number before `dB`. This doesn't seem overly complicated?

2023-08-03 02:54 UTC, praneethratna commented
> I think it would be ok? For the freqAB case, the `Hz/kHz/MHz/GHz` cases are fixed, so the number in front of that could be extracted. For the chanAB case, it is the string between the double quotes. The binary comparison operator `>, <, >=, <=, ==` are the allowed cases. And then we need to extracted the number before `dB`. This doesn't seem overly complicated?

@leewujung I think it shouldn't be overly complicated, it's just that i split everything into individual parts for better code debugging. I'll make these changes by today.

2023-08-03 17:16 UTC, praneethratna commented
@leewujung Even if use a single `re` expression to check for validity, we again need to use separate `re`' expressions to extract freq/chan values, operators and diff or am i understanding your point in a wrong way?

2023-08-09 12:52 UTC, praneethratna commented
@leewujung how do you suggest to do this?

2023-08-25 01:09 UTC, leewujung commented
Hi @praneethratna : sorry for my super late response. What I am thinking in terms of using `re` to grab out the pattern is like the following:
- use patterns like `"(?P<freqA>\d+)(?P<unitA>\w?)Hz"` to match freqA and freqB, for example:
  ```python
  a = re.match("(?P<freq>\d+)\s*(?P<unit>\w?)Hz", "120kHz") # also matches arbitrary space between "120" and "kHz"
  a["freq"]  # get the number associated with the frequency
  a["unit"]  # get the unit associated with the frequency
  ```
  then you can use `a["unit"]` to determine the right multiplication factor to get to the numbers in `frequency_nominal`, which is with units Hz (i.e. 120kHz is 120000 in `frequency_nominal`).
- you can use the pattern above to build up the whole pattern, something like the following:
  ```python
  freqA_pattern = "(?P<freqA>\d+)\s*(?P<unitA>\w?)Hz"
  freqA_pattern = "(?P<freqB>\d+)\s*(?P<unitB>\w?)Hz"
  db_pattern = "(?P<db>\d+)\s*dB"
  cmp_pattern = "\s*(?P<cmp>\S+?)\s*"
  DIFF_MATCHER = re.compile(freqA_pattern + "\s*-\s*" + freqB_pattern + cmp_pattern + db_pattern)
  ```
  and then use outputs of the matched results with some error checking and handling (like converting `str` to `float`, k to 1000 etc) to combine with your other parts of the code.

What do you think?

2023-08-25 20:02 UTC, praneethratna commented
> Hi @praneethratna : sorry for my super late response. What I am thinking in terms of using `re` to grab out the pattern is like the following:
> 
> * use patterns like `"(?P<freqA>\d+)(?P<unitA>\w?)Hz"` to match freqA and freqB, for example:
>   ```python
>   a = re.match("(?P<freq>\d+)\s*(?P<unit>\w?)Hz", "120kHz") # also matches arbitrary space between "120" and "kHz"
>   a["freq"]  # get the number associated with the frequency
>   a["unit"]  # get the unit associated with the frequency
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   then you can use `a["unit"]` to determine the right multiplication factor to get to the numbers in `frequency_nominal`, which is with units Hz (i.e. 120kHz is 120000 in `frequency_nominal`).
> * you can use the pattern above to build up the whole pattern, something like the following:
>   ```python
>   freqA_pattern = "(?P<freqA>\d+)\s*(?P<unitA>\w?)Hz"
>   freqA_pattern = "(?P<freqB>\d+)\s*(?P<unitB>\w?)Hz"
>   db_pattern = "(?P<db>\d+)\s*dB"
>   cmp_pattern = "\s*(?P<cmp>\S+?)\s*"
>   DIFF_MATCHER = re.compile(freqA_pattern + "\s*-\s*" + freqB_pattern + cmp_pattern + db_pattern)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   and then use outputs of the matched results with some error checking and handling (like converting `str` to `float`, k to 1000 etc) to combine with your other parts of the code.
> 
> What do you think?

@leewujung No worries! I understand it now, these suggestions helped me to refactor the code in a much simpler and clean way. I have made some assumptions while commiting the changes (related to `frequency_nominal`) and the test code which generates `frequency_nominal` which might require a change before we merge this.

2023-08-28 03:04 UTC, leewujung commented
@praneethratna : there are still places where you use `sympy` in the code. Could you remove them completely and use `re` instead? Thanks!

2023-08-28 08:03 UTC, praneethratna commented
@leewujung I have removed the usage of `sympy' completely and also squashed all the commits into one.

2023-08-31 15:16 UTC, leewujung commented on echopype/mask/api.py
>          raise ValueError("Only freqAB or chanAB must be given, but not both!")
minor wording tweak
```suggestion
    elif (freqABEq is not None) and (chanABEq is not None):
        raise ValueError("Only one of freqAB or chanAB should be given, but not both!")
```

2023-08-31 15:37 UTC, leewujung reviewed
@praneethratna : Thanks for this great PR!! It is awesome to have this intuitive way of putting in the freq diff equations.

I have some small suggestions for the organization and the tests:
- Since in #1142 there are more functions added to the `mask` subpackage, how about in this PR moving the frequency-differencing-related functions (`_check_source_Sv_freq_diff` and `check_freq_diff_and_parse_arguments`) to a separate module, say `echopype/mask/freq_diff.py` and keep the main API function `frequency_differencing` in `echopype/mask/api.py`? 
- for the tests, currently `test_frequency_differencing` is more of an integrated test, and in it the frequency units are all Hz so the unit matching was not tested. How about adding another set of tests to test for the function you wrote `check_freq_diff_and_parse_arguments`? This way you can test parsed element values and xfail the ones that should fail, etc.
- I suggest renaming `check_freq_diff_and_parse_arguments` to `_parse_freq_diff_eq` for the sake of clarity and also making it shorter

2023-08-31 15:51 UTC, leewujung commented
Also, I caught a bug / undesired behavior in the current `_check_source_Sv_freq_diff` function. In the current implementation, the values of `frequency_nominal` is not allowed to be duplicated:
https://github.com/OSOceanAcoustics/echopype/blob/254ee106eb580959ca85f2131168c4f17c0a285a/echopype/mask/api.py#L463-L467

However, it is possible that there are 2 channels (with different `channel` strings) that have the same `frequency_nominal` values (this is actually why we decided to use `channel` as the coordinate, instead of `frequency_nominal`, since coordinates cannot have duplicated values), and users may want to diff these 2 channels using the `chanABEq`.  I think that potentially duplicated `frequency_nominal` values should only be checked if people use `freqABEq` to put in their equation.

Looking at the code again, what do you think if we take the following approach to change this function?
- keep the first checks `# check that channel and frequency nominal are in source_Sv` intact
- for the below three checks, make it such that only `freqAB` checks are executed when people use `freqABEq`, and only `chanAB` checks are executed when people use `chanABEq`
  ```
  # make sure that the channel and frequency_nominal values are not repeated in source_Sv
  # check that the elements of freqAB are in frequency_nominal
  # check that the elements of chanAB are in channel
  ```
   ie we only check for `frequency_nominal` to not be duplicated and elements of `freqAB` are in `frequency_nominal` when people use `freqABEq`, and only check for `channel` to not be duplicated and elements of `chanAB` are in `channel` when people use `chanABEq`.

2023-08-31 20:22 UTC, leewujung commented on echopype/tests/mask/test_mask.py
> +        (None, '"chan2-12 89" - "chan4 89-12" >= 1.0 dB'),
These variations are great! I can see that the current test makes sure that `_parse_freq_diff_eq` is run through without problem, though the values are not checked. Could you add a section in the test for the parsed values, to make sure the output is correct? Thanks!

2023-08-31 20:28 UTC, leewujung commented on echopype/mask/freq_diff.py
> +        )
I would suggest consolidating the above to improve readability:
```python
# raise error if freqAB and chanAB are both None or both have values
if ...
   raise ValueError("...")

if freqAB is not None:
   # test if frequency_nominal values are not repeated in source_Sv
   # check that the elements of freqAB are in frequency_nominal
else:  # this implies chanAB is not None
   # test if channel values are not repeated in source_Sv
   # check that the elements of chanAB are in frequency_nominal
```

2023-08-31 20:37 UTC, leewujung commented on echopype/tests/mask/test_mask.py
> +        pytest.param(5, 4, True, True, None, ['chan1', 'chan9'],
I'd suggest another 2 cases where you xfail duplicated `freqAB` and duplicated `chanAB` cases, just to be complete.

2023-08-31 20:38 UTC, leewujung requested changes
Thanks @praneethratna for your speedy changes! I added some suggestions, and I think once they are addressed we can merge this PR. :)

2023-08-31 21:15 UTC, leewujung approved these changes
@praneethratna : Thanks a lot for your contribution. We can merge this PR now!

2023-08-31 21:21 UTC, leewujung commented
Ugh sorry just remember one thing. In here
https://github.com/OSOceanAcoustics/echopype/blob/254ee106eb580959ca85f2131168c4f17c0a285a/echopype/tests/utils/test_processinglevels_integration.py#L106
`frequency_differencing` is called (this is something the CI does not catch, unless one uses [all tests ci] (see [here](https://echopype.readthedocs.io/en/latest/contributing.html#continuous-integration-github-actions)). Could you quickly change it? Then I will merge. Thank you!

2023-08-31 21:57 UTC, merged