Fix EK80 CW angle test
OSOceanAcoustics/echopype pull request #319
Opened 2021-05-02 05:47 UTC by ngkavin

The EK80 CW angle test now works. The proposed dtype changes to the parser was already implemented, so only the test was touched.

2021-05-02 06:08 UTC, leewujung commented
@ngkavin : I guess I had fixed that angle parsing back when we started using the pyecholab then, and forgot about it. I know that I did some comparison between the RAW0 and RAW3 angle data.

If I understand correctly the only thing you changed in the code was `atol=1e-5` --> `atol=1e-4` to make the test pass. 
There is a systematic difference from small to large as the range increase (you should plot to check), which I do not understand.

2021-05-02 06:08 UTC, leewujung requested changes

2021-05-02 06:08 UTC, leewujung commented on echopype/tests/test_convert_ek80.py
> +    ]
These files are not on the Google drive.

2021-05-03 04:57 UTC, ngkavin commented
> If I understand correctly the only thing you changed in the code was `atol=1e-5` --> `atol=1e-4` to make the test pass.

I also changed the `isel` values which were hard-coded for some reason as well as changing the `zip` to `enumerate`, but yes, there were very little changes needed to get the test working.

> There is a systematic difference from small to large as the range increase (you should plot to check), which I do not understand.

Can you elaborate on this? Are you referring to these spikes when plotting the difference?
![image](https://user-images.githubusercontent.com/43619177/116842398-4cadd380-ab91-11eb-8b4e-b914be3ce231.png)

2021-05-03 17:11 UTC, leewujung commented
great, thanks for the clarification, I'll look into the changes now. 

> Can you elaborate on this? Are you referring to these spikes when plotting the difference?
yes this is one view of that: I remember seeing more deviation at longer ranges, which seems to show up in your diff plot that the deviations are more numerous at longer ranges.

2021-05-03 18:27 UTC, leewujung commented
@ngkavin : I changed a few things by pushing directly to your fork:
- The `ping_idx` selection was actually _not_ supposed to work if the EchoView test data set and echopype outputs have the same number of pings.  The test only passed because the first ping was not exported in EchoView
- Selecting frequency using `isel` in this case is risky because there is no guarantee the frequency coordinate is ordered with increasing values.
- I used a tighter bound for testing. The max diff is actually different for different frequency channels.

I added a TODO to change everything to use echodata attribute directly instead of saving files and read from them. 
Please do this for this file so that we can merge. 
Please do the same for everything in `test_calibrate.py` and `test_convert_...py` in a separate PR.

2021-05-03 22:09 UTC, leewujung approved these changes

2021-05-03 22:09 UTC, merged